# Docker compose file for local testing
services:
  # The RabbitMQ instance for inter-server communication
  # This image comes with an admin frontend available at http://localhost:15672, login with guest:guest
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # The Mariadb database
  # login is root:root
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
