# Docker compose file for local testing
services:
  # The Mariadb database
  # login with root:root
  mariadb:
    image: mariadb:latest@sha256:f1bba652ba57bea3099ca2fe1af692af537c27d96e0bcde39dce29e2ba1ec4f3
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
