name: Questions
description: "Questions you have about either the plugin or plugin related things"
labels: ["question"]

body:   
  - type: textarea
    id: Question
    attributes:
      label: "Question"
      placeholder: "What do you want to know?
